import { ExplanationData } from "../components/ExplanationColumn/ExplanationColumn";

export interface Block {
  title: string;
  code: string;
  language?: string;
  unique?: boolean;
  explanation: ExplanationData;
}

export interface ColumnData {
  number: number;
  title: string;
  blocks: Block[];
}

export const Data: ColumnData[] = [
  {
    number: 1,
    title: "Fundamentals",
    blocks: [
      {
        title: "Variables",
        code: `let x = 42;`,
        language: "js",
        explanation: {
          blockTitle: "Variables",
          what: "A variable is a named container for a value. In modern JavaScript, you declare variables with `let` (mutable) or `const` (immutable binding).",
          how: "`let` creates a block‑scoped variable that can be reassigned. It is hoisted but not initialised, so referencing it before declaration causes a `ReferenceError` (temporal dead zone).",
          example: `let count = 0;\ncount = count + 1;\nconsole.log(count); // 1\n\nif (true) {\n  let blockScoped = "inside";\n  console.log(blockScoped); // inside\n}\n// console.log(blockScoped); // ReferenceError`,
          tip: "Prefer `const` by default. Use `let` only when you truly need to reassign the variable.",
          version: "ES6",
          difficulty: "beginner",
          memoryUsage: 8,
        },
      },
      {
        title: "Constants",
        code: `const PI = 3.14;`,
        language: "js",
        explanation: {
          blockTitle: "Constants",
          what: "`const` declares a constant reference to a value, not an immutable value. The binding cannot be reassigned, but the contents of objects or arrays can still change.",
          how: "`const` is block‑scoped and also has a temporal dead zone. Always initialise a `const` declaration immediately.",
          example: `const name = "Alice";\n// name = "Bob"; // TypeError: Assignment to constant variable\n\nconst user = { age: 30 };\nuser.age = 31;       // allowed – the object is not frozen\nconsole.log(user.age); // 31\n\n// To make the value itself immutable, use Object.freeze()\nconst frozen = Object.freeze({ key: "val" });\n// frozen.key = "new"; // silently ignored in non‑strict, TypeError in strict mode`,
          tip: "Default to `const`. It signals intent and prevents accidental reassignments.",
          version: "ES6",
          difficulty: "beginner",
          memoryUsage: 8,
        },
      },
      {
        title: "Data Types",
        code: `typeof "hello";`,
        language: "js",
        explanation: {
          blockTitle: "Data Types",
          what: "JavaScript has seven primitive data types (string, number, bigint, boolean, undefined, symbol, null) and one structural type (object). The `typeof` operator helps inspect them.",
          how: "`typeof` returns a string indicating the type. Note that `typeof null` returns `'object'` – a historical bug. Functions are objects but `typeof` returns `'function'`.",
          example: `console.log(typeof "hello");   // "string"\nconsole.log(typeof 42);        // "number"\nconsole.log(typeof true);      // "boolean"\nconsole.log(typeof undefined); // "undefined"\nconsole.log(typeof null);      // "object" (quirk)\nconsole.log(typeof Symbol());  // "symbol"\nconsole.log(typeof {});        // "object"\nconsole.log(typeof []);        // "object"\nconsole.log(typeof function(){}); // "function"`,
          tip: "Use `Array.isArray()` or `instanceof` for more precise checks because `typeof` alone cannot distinguish arrays from plain objects.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 0,
        },
      },
      {
        title: "Operators",
        code: `5 + 2;`,
        language: "js",
        explanation: {
          blockTitle: "Operators",
          what: "Operators perform actions on values. Arithmetic (`+`, `-`, `*`, `/`, `%`), assignment (`=`), comparison (`===`, `!==`, `>`, `<`), and logical (`&&`, `||`, `!`) are the most common.",
          how: "Strict equality `===` compares both value and type without coercion, while `==` attempts type coercion. Always prefer `===` to avoid surprises.",
          example: `console.log(5 + 3);        // 8\nconsole.log(10 % 3);       // 1\nconsole.log("5" === 5);    // false\nconsole.log("5" == 5);     // true (coercion)\nconsole.log(true && false); // false\nconsole.log(true || false); // true\nconsole.log(!true);         // false`,
          tip: "Stick to strict equality `===` (and `!==`) unless you explicitly need type‑coercion. It makes your intentions clearer.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 0,
        },
      },
      {
        title: "Comments",
        code: `// This is a comment`,
        language: "js",
        explanation: {
          blockTitle: "Comments",
          what: "Comments are non‑executable notes that explain code. Single‑line comments start with `//`, multi‑line comments are enclosed in `/* ... */`.",
          how: "Write comments that describe *why* rather than *what*. They can also be used to temporarily disable code.",
          example: `// Compute the sum of two numbers\nfunction sum(a, b) {\n  /* Debugging tip:\n     check inputs before adding */\n  return a + b;\n}\n\n// TODO: Add error handling for non‑numbers\nlet result = sum(2, 3); // result = 5`,
          tip: "Keep comments up‑to‑date. Outdated comments are worse than no comments.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 0,
        },
      },
    ],
  },
  {
    number: 2,
    title: "Control Flow",
    blocks: [
      {
        title: "if / else",
        code: `if (x > 0) {\n  // positive\n} else {\n  // other\n}`,
        language: "js",
        explanation: {
          blockTitle: "if / else",
          what: "Conditional statements let your program take different paths based on whether a condition is truthy or falsy.",
          how: "The expression inside `if(...)` is evaluated. If it's truthy the first block runs; otherwise the `else` block (if present) runs. Chain multiple conditions with `else if`.",
          example: `const score = 75;\nlet grade;\n\nif (score >= 90) {\n  grade = "A";\n} else if (score >= 80) {\n  grade = "B";\n} else if (score >= 70) {\n  grade = "C";\n} else {\n  grade = "F";\n}\n\nconsole.log(grade); // C`,
          tip: "For simple true/false assignments, the ternary operator `condition ? exprIfTrue : exprIfFalse` is often cleaner.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 0,
        },
      },
      {
        title: "switch",
        code: `switch(day) {\n  case 1: console.log("Mon"); break;\n  default: console.log("??");\n}`,
        language: "js",
        explanation: {
          blockTitle: "switch",
          what: "`switch` compares a value against multiple `case` labels and executes the matching branch. It's an alternative to long `if/else if` chains.",
          how: "Strict comparison (`===`) is used. Without a `break`, execution “falls through” to the next case. The `default` case runs if no match is found.",
          example: `const day = 3;\nlet dayName;\n\nswitch (day) {\n  case 1:\n    dayName = "Monday";\n    break;\n  case 2:\n    dayName = "Tuesday";\n    break;\n  case 3:\n    dayName = "Wednesday";\n    break;\n  default:\n    dayName = "Unknown";\n}\n\nconsole.log(dayName); // Wednesday`,
          tip: "Always include a `default` case, even if it just logs a warning. Missing `break` statements are a common bug – consider using a linter.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 0,
        },
      },
      {
        title: "for loop",
        code: `for (let i = 0; i < 5; i++) {\n  console.log(i);\n}`,
        language: "js",
        explanation: {
          blockTitle: "for loop",
          what: "A `for` loop repeats a block of code a known number of times. It consists of an initialisation, a condition, and a final‑expression (usually increment).",
          how: "The loop runs while the condition remains true. All three parts are optional, but the condition is essential to avoid an infinite loop.",
          example: `for (let i = 0; i < 3; i++) {\n  console.log("Iteration", i);\n}\n// Output:\n// Iteration 0\n// Iteration 1\n// Iteration 2\n\n// Loop over an array\nconst items = ["a", "b", "c"];\nfor (let i = 0; i < items.length; i++) {\n  console.log(items[i]);\n}`,
          tip: "When iterating over arrays, prefer `for...of` or `Array.forEach()` for cleaner code, unless you need the index for manipulation.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 8,
        },
      },
      {
        title: "while loop",
        code: `while (x > 0) { x--; }`,
        language: "js",
        explanation: {
          blockTitle: "while loop",
          what: "A `while` loop repeats a block as long as its condition remains true. It's useful when the number of iterations is not known in advance.",
          how: "The condition is checked before each iteration. If it's false initially, the body never executes. Ensure the condition eventually becomes false to avoid infinite loops.",
          example: `let remaining = 3;\nwhile (remaining > 0) {\n  console.log(remaining);\n  remaining--;\n}\n// Output: 3, 2, 1\n\n// do...while variant (body runs at least once)\nlet x = 0;\ndo {\n  console.log("runs at least once");\n  x++;\n} while (x < 0); // false, but body already executed`,
          tip: "When the number of iterations is predetermined, a `for` loop is usually more readable and less error‑prone.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 8,
        },
      },
      {
        title: "break / continue",
        code: `for (let i = 0; i < 10; i++) {\n  if (i === 3) break;\n}`,
        language: "js",
        explanation: {
          blockTitle: "break / continue",
          what: "`break` immediately exits the innermost loop or `switch`. `continue` skips the rest of the current iteration and proceeds to the next one.",
          how: "Both can be used in all loop types (`for`, `while`, `do...while`). They can also work with labels to break outer loops.",
          example: `for (let i = 0; i < 5; i++) {\n  if (i === 2) continue; // skip 2\n  console.log(i); // 0, 1, 3, 4\n\nouter: for (let a = 0; a < 3; a++) {\n  for (let b = 0; b < 3; b++) {\n    if (a === 1 && b === 1) break outer; // exit both loops\n    console.log(a, b);\n  }\n}`,
          tip: "Overusing `break` and `continue` can make loops hard to follow. Consider refactoring the loop body into a function and using `return` for clarity.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 0,
        },
      },
    ],
  },
  {
    number: 3,
    title: "Functions",
    blocks: [
      {
        title: "Function Declaration",
        code: `function greet(name) {\n  return "Hello " + name;\n}`,
        language: "js",
        explanation: {
          blockTitle: "Function Declaration",
          what: "A function declaration defines a named function that can be called later. It is hoisted, so it can be used before its definition in the same scope.",
          how: "Use the `function` keyword followed by the name, parameters, and body. The `return` statement sends a value back to the caller; if omitted, the function returns `undefined`.",
          example: `console.log(sum(3, 4)); // 7 – hoisting allows calling before definition\n\nfunction sum(a, b) {\n  return a + b;\n}\n\nfunction logMessage() {\n  console.log("No return value");\n}\n\nconst result = logMessage(); // undefined`,
          tip: "Function declarations are great for top‑level utility functions. For callbacks or inline logic, arrow functions are more concise.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 48,
        },
      },
      {
        title: "Function Expression",
        code: `const add = function(a, b) {\n  return a + b;\n};`,
        language: "js",
        explanation: {
          blockTitle: "Function Expression",
          what: "A function expression assigns an anonymous (or named) function to a variable. Unlike declarations, they are not hoisted – you must define them before use.",
          how: "Assign `function(...) { ... }` to a `const` or `let`. The variable holds a reference to the function object.",
          example: `// add(2,3); // Error: Cannot access before initialization\nconst add = function(a, b) {\n  return a + b;\n};\nconsole.log(add(2, 3)); // 5\n\n// Named function expression (useful for recursion or debugging)\nconst factorial = function fact(n) {\n  return n <= 1 ? 1 : n * fact(n - 1);\n};\nconsole.log(factorial(5)); // 120`,
          tip: "Prefer `const` for function expressions to prevent accidental reassignment. Arrow functions are often a shorter alternative.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 48,
        },
      },
      {
        title: "Arrow Functions",
        code: `const add = (a, b) => a + b;`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Arrow Functions",
          what: "Arrow functions provide a shorter syntax and do not bind their own `this`, `arguments`, or `super`. They are excellent for short callbacks.",
          how: "If the body is a single expression, braces and the `return` keyword can be omitted. For a block body, use `{}` with an explicit `return`.",
          example: `// Concise\nconst double = x => x * 2;\n\n// Multi‑line\nconst greet = name => {\n  const message = \`Hello \${name}\`;\n  return message;\n};\n\n// Lexical \`this\`\nconst obj = {\n  value: 10,\n  log: function() {\n    setTimeout(() => console.log(this.value), 1000); // 10\n  }\n};\nobj.log();`,
          tip: "Arrow functions are perfect for callbacks because they inherit `this` from the surrounding scope. Avoid them for object methods that need their own `this`.",
          version: "ES6",
          difficulty: "beginner",
          memoryUsage: 48,
        },
      },
      {
        title: "Rest Parameters",
        code: `function sum(...nums) {\n  return nums.reduce((a,b) => a + b, 0);\n}`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Rest Parameters",
          what: "Rest parameters collect all remaining arguments into a real array. It replaces the need for the `arguments` object in most cases.",
          how: "Prefix the last parameter with `...`. Inside the function, that parameter is an array containing all extra arguments. Only one rest parameter is allowed, and it must be the last.",
          example: `function logAll(separator, ...strings) {\n  console.log(strings.join(separator));\n}\n\nlogAll(" - ", "Alice", "Bob", "Charlie");\n// Alice - Bob - Charlie\n\n// Destructuring with rest\nconst [first, ...rest] = [1, 2, 3, 4];\nconsole.log(first); // 1\nconsole.log(rest);  // [2, 3, 4]`,
          tip: "Rest parameters are always preferred over the older `arguments` object because they are genuine arrays and work with array methods.",
          version: "ES6",
          difficulty: "intermediate",
          memoryUsage: 24,
        },
      },
      {
        title: "Default Parameters",
        code: `function greet(name = "Guest") {\n  return "Hello " + name;\n}`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Default Parameters",
          what: "Default parameters allow a function to be called with fewer arguments. Missing or `undefined` parameters are replaced with the default value.",
          how: "Assign a value directly in the parameter list with `=`. The default is evaluated at call time, so it can even reference earlier parameters.",
          example: `function createUser(name, role = "user") {\n  console.log(\`\${name} is a \${role}\`);\n}\n\ncreateUser("Alice");           // Alice is a user\ncreateUser("Bob", "admin");    // Bob is an admin\n\n// Default using previous parameter\nfunction multiply(a, b = a * 2) {\n  return a * b;\n}\nconsole.log(multiply(3));    // 9 (3 * 6)\nconsole.log(multiply(3, 4)); // 12`,
          tip: "Put parameters with defaults after required ones to avoid passing `undefined` explicitly.",
          version: "ES6",
          difficulty: "beginner",
          memoryUsage: 4,
        },
      },
    ],
  },
  {
    number: 4,
    title: "Objects & Arrays",
    blocks: [
      {
        title: "Object Literal",
        code: `const user = { name: "Alice", age: 30 };`,
        language: "js",
        explanation: {
          blockTitle: "Object Literal",
          what: "An object literal is a comma‑separated list of key‑value pairs wrapped in `{}`. Keys are strings (or Symbols), and values can be any type, including functions (methods).",
          how: "Create an object by simply writing `{ key: value }`. Access properties with dot notation (`obj.key`) or bracket notation (`obj['key']`).",
          example: `const person = {\n  firstName: "Bob",\n  age: 25,\n  sayHello() {\n    console.log(\`Hi, I'm \${this.firstName}\`);\n  }\n};\n\nconsole.log(person.firstName);    // Bob\nconsole.log(person["age"]);       // 25\nperson.sayHello();                // Hi, I'm Bob\n\n// Shorthand property names (ES6)\nconst name = "Alice", age = 30;\nconst user2 = { name, age };      // { name: "Alice", age: 30 }`,
          tip: "Use dot notation when you know the property name at author time. Bracket notation is useful when the property name is dynamic.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 32,
        },
      },
      {
        title: "Array",
        code: `const arr = [1, 2, 3];`,
        language: "js",
        explanation: {
          blockTitle: "Array",
          what: "An array is an ordered, integer‑indexed collection of values. It's actually a special kind of object with a `length` property and many helpful methods.",
          how: "Create with square brackets `[]`. Elements are accessed via zero‑based index. The `length` property auto‑updates.",
          example: `const fruits = ["apple", "banana", "cherry"];\nconsole.log(fruits[0]);      // apple\nconsole.log(fruits.length);  // 3\n\nfruits.push("date");\nconsole.log(fruits.length);  // 4\n\nfruits.forEach((fruit, i) => {\n  console.log(i, fruit);\n});\n// 0 apple, 1 banana, 2 cherry, 3 date`,
          tip: "Prefer `map`, `filter`, `find`, `reduce` and other array methods for data transformation – they are more declarative and less error‑prone than manual loops.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 40,
        },
      },
      {
        title: "Array Methods (map, filter, reduce)",
        code: `const doubled = nums.map(n => n * 2);`,
        language: "js",
        explanation: {
          blockTitle: "Array Methods",
          what: "`map`, `filter`, and `reduce` are higher‑order functions that process arrays without mutating the original. They return new arrays (or a single value for `reduce`).",
          how: "`map` transforms every element; `filter` keeps elements that satisfy a predicate; `reduce` accumulates a single result. All take a callback function.",
          example: `const numbers = [1, 2, 3, 4, 5];\n\n// map\nconst squares = numbers.map(n => n ** 2);\nconsole.log(squares); // [1, 4, 9, 16, 25]\n\n// filter\nconst evens = numbers.filter(n => n % 2 === 0);\nconsole.log(evens); // [2, 4]\n\n// reduce\nconst sum = numbers.reduce((acc, n) => acc + n, 0);\nconsole.log(sum); // 15`,
          tip: "Chain these methods for powerful data pipelines: `arr.filter(...).map(...).reduce(...)`. Each step is independent and easy to debug.",
          version: "ES5 (with ES6 arrow example)",
          difficulty: "intermediate",
          memoryUsage: 40,
        },
      },
      {
        title: "Destructuring",
        code: `const { name, age } = user;`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Destructuring",
          what: "Destructuring unpacks values from arrays or properties from objects into distinct variables, making it easy to extract data.",
          how: "Use `{}` for objects and `[]` for arrays. You can assign default values and rename variables. Nested destructuring is also supported.",
          example: `const user = { name: "Alice", age: 28, city: "NYC" };\nconst { name, age } = user;\nconsole.log(name, age); // Alice 28\n\n// Array destructuring\nconst colors = ["red", "green", "blue"];\nconst [first, , third] = colors;\nconsole.log(first, third); // red blue\n\n// Default values + renaming\nconst { city: town = "Unknown" } = {};\nconsole.log(town); // Unknown`,
          tip: "Destructure function parameters directly for cleaner code: `function display({ name, age }) { ... }`.",
          version: "ES6",
          difficulty: "intermediate",
          memoryUsage: 8,
        },
      },
      {
        title: "Spread Operator",
        code: `const arr2 = [...arr1, 4, 5];`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Spread Operator",
          what: "The spread operator (`...`) expands an iterable (like an array) or object properties into individual elements or key‑value pairs.",
          how: "In arrays, `[...arr]` creates a shallow copy. In objects, `{...obj}` copies own enumerable properties. Use it to merge arrays/objects or to pass array elements as function arguments.",
          example: `const a = [1, 2, 3];\nconst b = [...a, 4, 5];   // [1, 2, 3, 4, 5]\nconst c = [0, ...a, 6];    // [0, 1, 2, 3, 6]\n\n// Object spread\nconst defaults = { theme: "light", fontSize: 14 };\nconst userSettings = { fontSize: 16, showSidebar: true };\nconst merged = { ...defaults, ...userSettings };\nconsole.log(merged); // { theme: "light", fontSize: 16, showSidebar: true }\n\n// Function arguments\nconsole.log(Math.max(...a)); // 3`,
          tip: "Spread performs shallow copy – nested objects are still shared. For deep cloning use `structuredClone()` or a dedicated library.",
          version: "ES6",
          difficulty: "intermediate",
          memoryUsage: 40,
        },
      },
    ],
  },
  {
    number: 5,
    title: "Asynchronous JavaScript",
    blocks: [
      {
        title: "Callbacks",
        code: `setTimeout(() => console.log("later"), 1000);`,
        language: "js",
        explanation: {
          blockTitle: "Callbacks",
          what: "A callback is a function passed as an argument to another function, to be executed after an operation completes. It was the original pattern for handling asynchronous results.",
          how: "The caller invokes the callback with the result (or error). Deeply nested callbacks can lead to “callback hell”, making the code hard to read.",
          example: `function fetchData(url, callback) {\n  // Simulating an async request\n  setTimeout(() => {\n    if (url === "/bad") {\n      callback(new Error("Invalid URL"), null);\n    } else {\n      callback(null, { data: "some data from " + url });\n    }\n  }, 500);\n}\n\nfetchData("/users", (err, data) => {\n  if (err) {\n    console.error(err);\n    return;\n  }\n  console.log(data);\n});`,
          tip: "In modern code, prefer Promises or `async/await` for better readability and error handling. Use callbacks only when required by an API.",
          version: "ES5",
          difficulty: "intermediate",
          memoryUsage: 48,
        },
      },
      {
        title: "Promises",
        code: `fetch(url).then(res => res.json());`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Promises",
          what: "A Promise is an object representing the eventual completion (or failure) of an asynchronous operation. It provides `.then()`, `.catch()`, and `.finally()` methods.",
          how: "Create a promise with `new Promise((resolve, reject) => { ... })`. Chain `.then()` to handle the fulfilled value, and `.catch()` to handle errors.",
          example: `const promise = new Promise((resolve, reject) => {\n  setTimeout(() => resolve("done"), 1000);\n});\n\npromise\n  .then(result => console.log(result)) // "done"\n  .catch(err => console.error(err));\n\n// Parallel execution\nPromise.all([\n  fetch("/api/users").then(r => r.json()),\n  fetch("/api/posts").then(r => r.json())\n]).then(([users, posts]) => {\n  console.log(users, posts);\n});`,
          tip: "Always handle rejections – unhandled promise rejections can crash Node.js processes. Use `.catch()` or `try/catch` with `async/await`.",
          version: "ES6",
          difficulty: "intermediate",
          memoryUsage: 64,
        },
      },
      {
        title: "Async / Await",
        code: `async function getData() {\n  const res = await fetch(url);\n  return res.json();\n}`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Async / Await",
          what: "`async/await` is syntactic sugar over Promises, allowing you to write asynchronous code that reads like synchronous code.",
          how: "Mark a function with `async` to enable the `await` keyword inside it. `await` pauses execution until the promise settles, then returns the resolved value.",
          example: `async function fetchUser(id) {\n  try {\n    const response = await fetch(\`/api/users/\${id}\`);\n    if (!response.ok) throw new Error("Network error");\n    const user = await response.json();\n    console.log(user);\n    return user;\n  } catch (error) {\n    console.error("Fetch failed:", error);\n  }\n}\n\nfetchUser(1);`,
          tip: "Don't mix `.then()` chains with `await` in the same function – choose one style for consistency. `async/await` is usually more readable.",
          version: "ES2017",
          difficulty: "intermediate",
          memoryUsage: 64,
        },
      },
      {
        title: "setTimeout / setInterval",
        code: `setTimeout(() => console.log("once"), 1000);`,
        language: "js",
        explanation: {
          blockTitle: "setTimeout / setInterval",
          what: "`setTimeout` schedules a function to run once after a delay. `setInterval` repeatedly calls a function with a fixed time delay between each call.",
          how: "Both return a timer ID that can be passed to `clearTimeout()` / `clearInterval()` to cancel the scheduled execution.",
          example: `// One‑time delay\nconst timer = setTimeout(() => {\n  console.log("Delayed message");\n}, 2000);\nclearTimeout(timer); // cancels it\n\n// Recurring\nlet count = 0;\nconst interval = setInterval(() => {\n  count++;\n  console.log(count);\n  if (count === 3) clearInterval(interval);\n}, 1000);\n// Output: 1, 2, 3 (each after 1 second)`,
          tip: "For animations, use `requestAnimationFrame()` instead of `setInterval` for smoother performance. Clean up intervals to prevent memory leaks.",
          version: "ES5",
          difficulty: "beginner",
          memoryUsage: 4,
        },
      },
      {
        title: "Error Handling (try/catch)",
        code: `try {\n  // risky code\n} catch (e) {\n  console.error(e);\n}`,
        language: "js",
        explanation: {
          blockTitle: "Error Handling",
          what: "`try/catch` allows you to catch runtime errors and handle them gracefully instead of crashing the script. The `finally` block runs regardless of the outcome.",
          how: "Wrap potentially failing code in `try`. If an error is thrown (or an `await`ed promise rejects), control jumps to `catch`. Use `finally` for cleanup.",
          example: `function parseJSON(str) {\n  try {\n    const result = JSON.parse(str);\n    console.log("Parsed:", result);\n    return result;\n  } catch (error) {\n    console.error("Invalid JSON:", error.message);\n    return null;\n  } finally {\n    console.log("Attempted to parse JSON");\n  }\n}\n\nparseJSON('{ "key": "value" }');  // works\nparseJSON("invalid");              // catches error`,
          tip: "In `catch`, the error parameter is of type `unknown` in TypeScript, but in JavaScript it can be anything thrown. Always check its type before accessing properties.",
          version: "ES5",
          difficulty: "intermediate",
          memoryUsage: 0,
        },
      },
    ],
  },
  {
    number: 6,
    title: "Modern ES6+",
    blocks: [
      {
        title: "Template Literals",
        code: `\`Hello \${name}\``,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Template Literals",
          what: "Template literals (backtick strings) allow embedded expressions and multi‑line strings without concatenation.",
          how: "Use backticks `` ` `` instead of quotes. Insert variables or expressions with `${...}`. Newlines inside the template are preserved.",
          example: `const name = "Alice";\nconst age = 30;\nconst greeting = \`Hello \${name}, you are \${age} years old.\`;\nconsole.log(greeting);\n\nconst multiLine = \`Line 1\nLine 2\nLine 3\`;\nconsole.log(multiLine);\n// Line 1\n// Line 2\n// Line 3`,
          tip: "Use template literals instead of string concatenation – they're cleaner and less error‑prone. They also support tagged templates for advanced formatting.",
          version: "ES6",
          difficulty: "beginner",
          memoryUsage: 0,
        },
      },
      {
        title: "Optional Chaining",
        code: `user?.address?.city`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Optional Chaining",
          what: "Optional chaining (`?.`) safely accesses deeply nested properties without having to check each intermediate reference for `null` or `undefined`.",
          how: "If the part before `?.` is `null` or `undefined`, the expression short‑circuits and returns `undefined`. Works for property access, function calls, and array indices.",
          example: `const user = { address: { city: "NYC" } };\nconsole.log(user?.address?.city); // "NYC"\nconsole.log(user?.profile?.bio);  // undefined (no error)\n\n// Optional call\nconst api = { getPosts: () => [1,2,3] };\napi.getPosts?.();          // [1,2,3]\napi.unknown?.();          // undefined\n\n// Optional array index\nconst arr = null;\nconsole.log(arr?.[0]);    // undefined`,
          tip: "Combine optional chaining with the nullish coalescing operator `??` to provide defaults: `const city = user?.address?.city ?? 'Unknown'`.",
          version: "ES2020",
          difficulty: "intermediate",
          memoryUsage: 0,
        },
      },
      {
        title: "Nullish Coalescing",
        code: `value ?? "default"`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Nullish Coalescing",
          what: "The nullish coalescing operator (`??`) returns the right‑hand operand when the left‑hand operand is `null` or `undefined`; otherwise it returns the left‑hand operand.",
          how: "Unlike `||`, it does not treat other falsy values like `0` or `''` as fallback triggers. This makes it safer for defaults where `0` or empty string are valid values.",
          example: `console.log(0 ?? "default");      // 0\nconsole.log("" ?? "default");     // ""\nconsole.log(null ?? "default");   // "default"\nconsole.log(undefined ?? "x");    // "x"\n\n// Compare with ||\nconsole.log(0 || "default");      // "default" (unwanted)\nconsole.log("" || "default");     // "default" (unwanted)`,
          tip: "Use `??` when you want a fallback exclusively for `null`/`undefined`. Use `||` when you want to catch any falsy value.",
          version: "ES2020",
          difficulty: "intermediate",
          memoryUsage: 0,
        },
      },
      {
        title: "Modules (import/export)",
        code: `import { func } from './module.js';`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Modules",
          what: "ES modules allow you to split code into reusable files. You can `export` variables, functions, or classes and `import` them in other files.",
          how: "Use `export default` for a single main export, and named `export` for multiple. The import statement uses a relative path and must have the file extension (in Node.js/browsers with module support).",
          example: `// math.js\nexport const PI = 3.14;\nexport function add(a, b) { return a + b; }\n\n// main.js\nimport { PI, add } from './math.js';\nconsole.log(PI);           // 3.14\nconsole.log(add(2, 3));   // 5\n\n// Default export\n// lib.js\nexport default function greet(name) { return \`Hello \${name}\`; }\n// usage\nimport greet from './lib.js';\nconsole.log(greet('Alice'));`,
          tip: "Stick to named exports for most cases – they make the API explicit and work better with IDE autocompletion.",
          version: "ES6",
          difficulty: "intermediate",
          memoryUsage: 0,
        },
      },
      {
        title: "Map & Set",
        code: `const map = new Map();\nmap.set('key', 'value');`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Map & Set",
          what: "`Map` is a collection of keyed data items where keys can be any type. `Set` is a collection of unique values.",
          how: "`Map` preserves insertion order and has methods like `set`, `get`, `has`, `delete`. `Set` stores distinct values and has `add`, `has`, `delete`.",
          example: `// Map\nconst map = new Map();\nmap.set("name", "Alice");\nmap.set(42, "answer");\nconsole.log(map.get("name")); // Alice\nconsole.log(map.has(42));     // true\n\n// Set\nconst set = new Set([1, 2, 2, 3]);\nconsole.log(set.size); // 3\nset.add(4);\nconsole.log(set.has(2)); // true\n\n// Iteration\nfor (const [key, val] of map) {\n  console.log(key, val);\n}`,
          tip: "Use `Map` when you need a dictionary with non‑string keys or reliable insertion order. Use `Set` to deduplicate arrays or manage unique collections.",
          version: "ES6",
          difficulty: "intermediate",
          memoryUsage: 32,
        },
      },
    ],
  },
  {
    number: 7,
    title: "Advanced Concepts",
    blocks: [
      {
        title: "Closures",
        code: `function outer() {\n  let x = 1;\n  return function() { return x; };\n}`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Closures",
          what: "A closure is a function that remembers its lexical scope even when the function is executed outside that scope. It “closes over” the variables of its outer function.",
          how: "When a function is created inside another function, it retains a reference to the outer variables. This is the foundation for data privacy and many functional programming patterns.",
          example: `function makeCounter() {\n  let count = 0;\n  return function() {\n    count++;\n    return count;\n  };\n}\n\nconst counter = makeCounter();\nconsole.log(counter()); // 1\nconsole.log(counter()); // 2\nconsole.log(counter()); // 3\n\n// Each invocation creates a separate closure\nconst another = makeCounter();\nconsole.log(another()); // 1`,
          tip: "Closures can lead to memory leaks if large data structures are retained unintentionally. Be mindful when creating closures inside loops; use `let` or a dedicated function to capture the current value.",
          version: "ES5",
          difficulty: "advanced",
          memoryUsage: 64,
        },
      },
      {
        title: "Prototypes",
        code: `function Dog(name) {\n  this.name = name;\n}\nDog.prototype.bark = function() {\n  console.log("Woof!");\n};`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Prototypes",
          what: "Every JavaScript object has an internal link to another object called its prototype. This prototype chain is the mechanism for inheritance and shared methods.",
          how: "Constructor functions use `.prototype` to define shared methods. Modern class syntax is largely sugar over this prototype‑based model.",
          example: `function Animal(name) {\n  this.name = name;\n}\nAnimal.prototype.speak = function() {\n  console.log(\`\${this.name} makes a sound\`);\n};\n\nconst dog = new Animal("Rex");\ndog.speak(); // Rex makes a sound\n\nconsole.log(dog.__proto__ === Animal.prototype); // true\nconsole.log(Animal.prototype.isPrototypeOf(dog)); // true`,
          tip: "Today you can use `class` syntax which is more readable, but understanding prototypes is essential for debugging and reading older code.",
          version: "ES5",
          difficulty: "advanced",
          memoryUsage: 32,
        },
      },
      {
        title: "`this` Keyword",
        code: `const obj = {\n  name: 'Alice',\n  greet() { return this.name; }\n};`,
        language: "js",
        explanation: {
          blockTitle: "`this` Keyword",
          what: "`this` refers to the execution context of a function. Its value is determined by how the function is called, not where it is defined (except for arrow functions).",
          how: "In a method, `this` is the object before the dot. In a regular function, it is the global object (or `undefined` in strict mode). Arrow functions capture `this` from their enclosing scope.",
          example: `const user = {\n  name: "Alice",\n  regularGreet: function() { console.log(this.name); },\n  arrowGreet: () => console.log(this.name) // 'this' is from outer scope (here global)\n};\n\nuser.regularGreet(); // Alice\n// user.arrowGreet();  // undefined or error depending on context\n\nfunction standalone() { console.log(this); }\nstandalone(); // window (or undefined in strict mode)`,
          tip: "Use arrow functions when you want to preserve the outer `this` (e.g., in callbacks). For object methods, stick to regular function expressions or method shorthand.",
          version: "ES5",
          difficulty: "advanced",
          memoryUsage: 0,
        },
      },
      {
        title: "Event Loop",
        code: `console.log('start');\nsetTimeout(() => console.log('async'), 0);\nconsole.log('end');`,
        language: "js",
        unique: true,
        explanation: {
          blockTitle: "Event Loop",
          what: "The event loop is JavaScript’s mechanism for handling asynchronous callbacks. It continuously checks the call stack and task queues, executing code in a non‑blocking fashion.",
          how: "Synchronous code runs first. Micro‑tasks (Promise callbacks) are processed before macro‑tasks (`setTimeout`, I/O). This is why `setTimeout(0)` still runs after the current synchronous block.",
          example: `console.log("1");\n\nsetTimeout(() => console.log("2"), 0);\n\nPromise.resolve().then(() => console.log("3"));\n\nconsole.log("4");\n\n// Output: 1, 4, 3, 2\n// Explanation: sync first, then micro‑task (3), then macro‑task (2)`,
          tip: "Understanding the event loop helps you predict the order of execution and avoid tricky race conditions. Use `async/await` to linearise asynchronous code.",
          version: "ES5",
          difficulty: "advanced",
          memoryUsage: 0,
        },
      },
      {
        title: "Strict Mode",
        code: `"use strict";`,
        language: "js",
        explanation: {
          blockTitle: "Strict Mode",
          what: "Strict mode is a restricted variant of JavaScript that eliminates some silent errors and improves performance by making the engine optimizations more predictable.",
          how: "Activate with `'use strict';` at the top of a script or function. It forbids undeclared variables, duplicate parameter names, and other common mistakes. ES modules are strict by default.",
          example: `"use strict";\n\nfunction sum(a, a) {\n  return a + a; // SyntaxError in strict mode\n}\n\nx = 10; // ReferenceError: x is not defined\nconsole.log(x);`,
          tip: "Always place `'use strict';` at the top of your scripts or functions. Modern ES modules are strict by default, so you rarely need to write it explicitly.",
          version: "ES5",
          difficulty: "intermediate",
          memoryUsage: 0,
        },
      },
    ],
  },
];
